[licenses]
allow = [
  "MIT",
  "ISC",
  "BSD-3-Clause",
  "Apache-2.0",
  "CC0-1.0",
  "OpenSSL",
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[bans]
multiple-versions = "allow"
